---
version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node

  zookeeper:
    image: zookeeper

  hbase:
    build:
      context: hbase
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8085:8085

  kafka:
    build:
      context: kafka
      dockerfile: Dockerfile
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

networks:
  default:
    driver: bridge