---
version: '3.7'
services:

  gocolly-consumer:
    image: x0rzkov/consumer-app:latest-alpine
    container_name: ${NAMESPACE}-consumer
    build:
      context: cmd/consumer
      dockerfile: Dockerfile
    environment:
    - KAFKA_SERVERS=kafka:9092
    - MONGO_HOST=mongodb:27017
    links:
    - mongodb:mobgodb
    - kafka:kafka
    depends_on:
    - mongodb
    - kafka
    networks:
    - internal
    - web

  gocolly-producer:
    image: x0rzkov/producer-app:latest-alpine
    container_name: ${NAMESPACE}-producer
    environment:
    - KAFKA_SERVERS=kafka:9092
    build:
      context: cmd/producer
      dockerfile: Dockerfile
    networks:
    - internal
    - web

  mongodb:
    image: mongo:latest
    container_name: ${NAMESPACE}-mongodb
    volumes:
    - mongo-data:/var/lib/mongodb/db
    - mongo-backup:/var/lib/backup
    ports:
    - 27017:27017
    networks:
    - internal
    - web

  mongoexpress:
    restart: always
    image: mongo-express
    container_name: ${NAMESPACE}-mongoexpress
    links:
    - mongodb:mongo
    environment:
    - VCAP_APP_PORT=8091
    - ME_CONFIG_MONGODB_AUTH_USERNAME=""
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=""
    depends_on:
    - mongodb
    ports:
    - 8091:8091
    networks:
    - internal
    - web

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: ${NAMESPACE}-elastic
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node
    networks:
    - internal
    - web

  zookeeper:
    image: zookeeper
    container_name: ${NAMESPACE}-zookeper
    networks:
    - internal
    - web
    hostname: zk
    ports:
    - 2181:2181
    networks:
    - internal
    - web

  hbase:
    image: x0rzkov/hbase:1.3.1-alpine
    container_name: ${NAMESPACE}-hbase
    build:
      context: .docker/hbase
      dockerfile: Dockerfile
    links:
    - zookeeper:zk
    hostname: hbase
    ports:
    - 8080:8080
    - 8085:8085
    - 60000:60000
    - 60010:60010
    - 60020:60020
    - 60030:60030
    - 8070:8070
    - 8090:8090
    networks:
    - internal
    - web

  kafka:
    image: x0rzkov/kafka:2.5.0-alpine
    container_name: ${NAMESPACE}-kafka
    build:
      context: .docker/kafka
      dockerfile: Dockerfile
    ports:
    - 9092:9092
    depends_on:
    - zookeeper
    links:
    - zookeeper:zk
    networks:
    - internal
    - web
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.56.102
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    container_name: ${NAMESPACE}-kafka-manager
    ports:
    - "9000:9000"
    links:
    - zookeeper:zk
    environment:
      ZK_HOSTS: "zk:2181"
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
    - internal
    - web
    command: -Dpidfile.path=/dev/null

networks:
  #default:
  #  driver: bridge
  internal:
  web:
    external: true  

volumes:
  mongo-data:
  mongo-backup:
